name: 'Pull Request'
on:
  pull_request:

permissions:
  contents: 'read'

jobs:
  golang:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8' # ratchet:actions/checkout@v5
        with:
          persist-credentials: false
      - name: 'setup go'
        uses: 'actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00' # ratchet:actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: 'fetch modules'
        run: 'go mod download'
      - name: 'go unit test'
        run: 'go test -v ./...'

  action-test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8' # ratchet:actions/checkout@v5
        with:
          persist-credentials: false
      - name: 'setup terraform'
        uses: 'hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd' # ratchet:hashicorp/setup-terraform@v3
        with:
          terraform_version: 'v1.7'
      - name: 'create plan'
        working-directory: 'test'
        run: |
          terraform init
          terraform plan -out=plan.bin
          terraform show -json plan.bin > plan.json
      - name: 'run action'
        id: 'origins'
        uses: './'
        with:
          terraform-dir: 'test'
          plan-json: 'test/plan.json'
          output-file: 'enriched.json'
      - name: 'verify output'
        run: |
          test -f enriched.json
          grep '"_loc"' enriched.json

