name: 'Pull Request'
on:
  pull_request:

jobs:
  golang:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8' # ratchet:actions/checkout@v5
      - name: 'setup go'
        uses: 'actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00' # ratchet:actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: 'fetch modules'
        run: 'go mod download'
      - name: 'go build'
        run: 'go build ./...'
      - name: 'go unit test'
        run: 'go test -v ./...'

  integration:
    needs:
      - 'golang'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8' # ratchet:actions/checkout@v5
      - name: 'setup go'
        uses: 'actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00' # ratchet:actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: 'cli build'
        run: |
          go build ./cmd/parse_locations
          go build ./cmd/merge_with_plan
      - name: 'setup terraform'
        uses: 'hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd' # ratchet:hashicorp/setup-terraform@v3
        with:
          terraform_version: 'v1.7'
      - name: 'create plan'
        working-directory: 'test'
        run: |
          terraform init
          terraform plan -out=plan.bin
          terraform show -json plan.bin > plan.json
      - name: 'parse locations'
        run: |
          ./parse_locations -dir="test" -out="locations.json"
      - name: 'merge with plan'
        run: |
          ./merge_with_plan -locs="locations.json" -plan="test/plan.json" -out="new_plan.json"
          cat new_plan.json
      - name: 'together with stdin/stdout'
        run: >-
          ./parse_locations -dir="test" -out="-" |
          ./merge_with_plan -locs="-" -plan="test/plan.json" -out="-"

# TODO: Actually compare the modified plan with jq.
